<!--
author: admin
date: 2012-04-08
title: dialyzer中的has no local return警告
tags: dialyzer,Erlang
category: Erlang
status: publish
summary: 今天用dialyzer分析项目代码，得到一行警告：db.erl:601: Function restore_not_active_data_begin/0 has no local return[erlang]%% @doc 开始恢复二级非活跃数据restore_not_acti
-->

今天用dialyzer分析项目代码，得到一行警告：
db.erl:601: Function restore_not_active_data_begin/0 has no local return
[erlang]
%% @doc 开始恢复二级非活跃数据
restore_not_active_data_begin() -&gt;
    lists:foreach(
      fun({Tab, NotActiveTab, _}) -&gt;
              case catch mnesia:table_info(NotActiveTab, all) of
                  {'EXIT', _} -&gt;
                      ignore;
                  _ -&gt;
                      mnesia:change_table_copy_type(NotActiveTab, node(), disc_copies),
                      [begin
                           Key = erlang:element(2, R),
                           case mnesia:dirty_read(Tab, Key) of
                               [] -&gt;
                                   mnesia:dirty_write(Tab, R);
                               _ -&gt;
                                   ignore
                           end
                       end || R &lt;- mnesia:dirty_match_object(NotActiveTab, mnesia:table_info(NotActiveTab, wild_pattern))],
                      mnesia:clear_table(NotActiveTab),
                      ok
              end
      end, db_persistent:get_active_table_map_list()), 
    mnesia:clear_table(?DB_NOT_ACTIVE_MAP_P),
    ok.
[/erlang]

原因挺奇怪，查了相关资料，原因是dialyzer认为如果发生了匹配出错，则函数是无法返回的；例如上述代码中 db_persistent:get_active_table_map_list()返回的是[{A,B}, …]这样的list，因此就有了上述警告。疑问：为何不是警告匹配出错？

另外的补充：
2. (http://mgmullis.wordpress.com/2009/09/10/dialyzer-warning-function-has-no-local-return/)
如果有函数 test原型定义如下：
-spec(test(list(), list()) -> ok).
在函数start中如此调用：
start() ->
test("hello", <<"world">>).
则start函数会有 no local return的警告。

3. (http://zerthurd.blogspot.com/2009/05/dialyzer-warning-no-local-return.html)
如果定义了record如下：
-record(state, {
name :: string(),
data :: binary()
}
使用如下：
init([]) ->
    {ok, #state{name = "Name", data = "Data"}}
同样也会发出警告

4.
定义如下函数：
abort(Reason) ->
erlang:throw({error, Reason}).

同样也会导致警告。

综合前三种情况，也就是说当dialyzer分析出来的类型描述同实际使用时的类型不同时就会有这样的警告，这个警告太不友好了。
第四种情况是猜测可能是上下文分析有难度（需要判断调用方是否进行了catch操作），解决办法：
-spec(abort(any()) -> no_return()).
